title: Vel-San's KF-1 Blog # The title of the blog
author: Vel-San # Your name
email: Vel-San@protonmail.com # your email shown in the footer
url: https://vel-san.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A blog that will hold all my <a href="http://www.killingfloorgames.com/">Killing floor 1</a> related contributions; guides, workshop items and favorite collections like Mutators, Maps and such.
favicon: "./favicon.png" # set the favicon of the site

# Timezone
timezone: Germany/Berlin
show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://i.imgur.com/nNT7g2P.jpg" # avatar in about page
  about_you: Just a Fresh Meat who decided to be a Flesh Pounder! # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.
  dark_mode: true
  # generate social links in about page.
  social_links:
    twitter: Vel__San
    github: Vel-San
    steam: Vel-San
    reddit: XerXesKay
    # reddit:

# Build settings
# theme: moving # Dev
theme: huangyz0918/moving # Production

plugins:
  - jekyll-feed
  - jekyll-seo-tag