title: Bleedin' Action Man # The title of the blog
author: Vel-San # Your name
email: Vel-San@protonmail.com # your email shown in the footer
url: https://vel-san.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Diary of an FBS.<br>
  A curated list of Guides, Mutators, Groups & Servers for <a href="http://www.killingfloorgames.com/">Killing Floor 1</a>;<br>
  All findings here are community picked/submitted;
favicon: "./favicon.png" # set the favicon of the site

# Timezone
timezone: Germany/Berlin
show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/a5/a5d5885d8a8d2e81c2738bcd3fa7d32c6a06e134_full.jpg" # avatar in about page | Dynamic as steam's profile picture!
  about_you: Fresh Meat aspiring to be a FleshPounder; # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.
  dark_mode: true
  # generate social links in about page.
  social_links:
    twitter: Vel__San
    github: Vel-San
    bam_github: Bleeding-Action-Man
    steam: Vel-San
    reddit: XerXesKay

# Build settings
# theme: moving # Dev
theme: huangyz0918/moving # Production

# Switch between dark and light: _sass for light and _sass-dark for dark
sass:
    sass_dir: _sass-dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# The URL for the staticman API bridge endpoint
staticman_url: https://kf-blog-comments-bot.herokuapp.com/v2/entry/vel-san/vel-san.github.io/master/comments

# reCaptcha
reCaptcha:
  siteKey: 6LenSvQUAAAAAPHYcsE7OCfIHh01L6xXIo6lS2SL
  secret: bS2i42MY3KRg6HxQaqDiNFM9aylCONM+lWgTAKQfBkG9d7fwfzOTNUPXyLlFTUgwtE36zQlWQf0qKLQ90y98EsCp8rcADz8RReXlIlC0yUJr5Pd0ZRl0bzvWJa7XS/6q/4BqSEC/YZxewPZ4lguRM/ATjuPn1VoSzDPyhqeqSTpzCbFjn6tFJ8BufjGL47uMNdZuod4Ov7BGwMc1qWF/WQf/N/G+PuuqqBJHu17pT1xIDYQ9smV6XpWXA12owNiMdV7erd9Ud+1q4Zv1iLOpV+nlEvB8zew70JZMb7aJglPktOvpijJX4NKMKIGa/fNoxW7DSEGEiyqzaGePKc8njd2mJexZd49y4v9VFbOFYpntdIdn4cOFWl3oeokItSbjtzNI3B5Eu87Pew07AcMgb9OJHnvIIARsiytp7A8F9OBwQrd4lXHoc5wKn8tpDQa8Xo1qXfXlBh3KKuW8kSfobECSH1yV2FsAL0YoIiWcLrZuGEiVjcJjhjBI8RwIdNTACO8KiEYonVibAruN4aqhS8WFqiwjdKY1K1j4iYbxJQk0A+Ya+qd/vNdUMUz7THmy87wpZteKL5N0/hvvu/rkeZznY2sfFVHVXcMFpBQPgHaJ9lfHXMsQ+RPB1w6fm2tr0mFIzKq66x3YGNF5rQZIPXDZ4V2E2mOGRoaJ35Pfwac=